# Generated by Django 4.1.7 on 2023-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Editorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_editorial",
                    models.CharField(max_length=200, verbose_name="Editorial"),
                ),
                (
                    "rut_editorial",
                    models.CharField(max_length=200, verbose_name="RUT Editorial"),
                ),
                (
                    "address_editorial",
                    models.CharField(max_length=200, verbose_name="Address Editorial"),
                ),
                (
                    "mail_editorial",
                    models.CharField(max_length=200, verbose_name="Email Editorial"),
                ),
            ],
            options={
                "verbose_name": "Editorial",
                "verbose_name_plural": "Editorials",
                "ordering": ["id"],
            },
        ),
        migrations.RemoveField(
            model_name="gender_literary",
            name="author",
        ),
    ]
