# Generated by Django 4.1.7 on 2023-08-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0002_editorial_remove_gender_literary_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
