# Generated by Django 4.1.7 on 2023-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0003_delete_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["id"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="name_Book",
            field=models.CharField(max_length=255, null=True, verbose_name="Book"),
        ),
    ]
