# Generated by Django 4.1.7 on 2023-08-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0004_alter_book_options_book_name_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="name_Book",
            field=models.CharField(max_length=255, null=True, verbose_name="Name Book"),
        ),
    ]
