# Generated by Django 4.1.7 on 2023-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0007_language_author_about_author_book_review_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="about_author",
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name="About Author"
            ),
        ),
    ]
