# Generated by Django 4.1.7 on 2023-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0008_alter_author_about_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="review",
            field=models.TextField(max_length=15000, null=True, verbose_name="Review"),
        ),
    ]
