# Generated by Django 4.1.7 on 2023-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0009_alter_book_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormatBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Format Book"
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Gender_Literary",
            new_name="GenderLiterary",
        ),
    ]
