# Generated by Django 4.1.7 on 2023-08-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0010_formatbook_rename_gender_literary_genderliterary"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="name_author",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.PROTECT,
                to="book_crm.author",
                verbose_name="Author",
            ),
            preserve_default=False,
        ),
    ]
