# Generated by Django 4.1.7 on 2023-08-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0011_book_name_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="book_crm.language",
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="size",
            field=models.CharField(max_length=7, null=True, verbose_name="Size Book"),
        ),
    ]
