# Generated by Django 4.1.7 on 2023-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0013_binding_category_alter_author_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="about_author",
            field=models.TextField(
                blank=True, max_length=5000, null=True, verbose_name="About Author"
            ),
        ),
    ]
