# Generated by Django 4.1.7 on 2023-08-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0014_alter_author_about_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="imgBook",
            field=models.ImageField(default=12, upload_to=""),
            preserve_default=False,
        ),
    ]
