# Generated by Django 4.1.7 on 2023-08-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0015_book_imgbook"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Binding",
        ),
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
        migrations.RemoveField(
            model_name="book",
            name="name_author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="name_gender",
        ),
        migrations.DeleteModel(
            name="Editorial",
        ),
        migrations.DeleteModel(
            name="FormatBook",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="GenderLiterary",
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
