# Generated by Django 4.1.7 on 2023-08-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0017_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Binding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("binding", models.CharField(max_length=200, verbose_name="Binding")),
            ],
            options={
                "verbose_name": "Binding",
                "verbose_name_plural": "Bindings",
                "ordering": ["id"],
            },
        ),
    ]
