# Generated by Django 4.1.7 on 2023-08-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0018_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormatBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Format Book"
                    ),
                ),
            ],
            options={
                "verbose_name": "Format",
                "verbose_name_plural": "Formats",
                "ordering": ["id"],
            },
        ),
    ]
