# Generated by Django 4.1.7 on 2023-08-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0023_alter_genderliterary_options_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="name_Book",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Name Book"
            ),
        ),
    ]
