# Generated by Django 4.1.7 on 2023-08-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0024_alter_book_name_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.IntegerField(default=24, verbose_name="Size Book"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="review",
            field=models.TextField(max_length=15000, null=True, verbose_name="Review"),
        ),
    ]
