# Generated by Django 4.1.7 on 2023-08-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0026_book_name_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="name_author",
        ),
    ]
