# Generated by Django 4.1.7 on 2023-08-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0029_book_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="size",
            field=models.CharField(max_length=9, verbose_name="Size Book"),
        ),
    ]
