# Generated by Django 4.1.7 on 2023-08-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0030_alter_book_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="book_crm.language",
                verbose_name="Language",
            ),
        ),
    ]
