# Generated by Django 4.1.7 on 2023-08-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0031_book_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=200, verbose_name="Category"),
        ),
    ]
