# Generated by Django 4.1.7 on 2023-08-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0032_alter_category_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="about_author",
            field=models.TextField(
                default=29, max_length=5000, verbose_name="About Author"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formatbook",
            name="format",
            field=models.CharField(max_length=200, verbose_name="Format Book"),
        ),
        migrations.AlterField(
            model_name="genderliterary",
            name="name_gender",
            field=models.CharField(max_length=200, verbose_name="Gender Literary"),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(max_length=200, verbose_name="Language"),
        ),
    ]
