# Generated by Django 4.1.7 on 2023-08-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0033_alter_author_about_author_alter_formatbook_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="imgBook",
            field=models.ImageField(default=33, upload_to=""),
            preserve_default=False,
        ),
    ]
