# Generated by Django 4.1.7 on 2023-08-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book_crm", "0034_book_imgbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="name_gender",
            field=models.ForeignKey(
                default=33,
                on_delete=django.db.models.deletion.PROTECT,
                to="book_crm.genderliterary",
                verbose_name="Gender Literary",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="imgBook",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
